### ISSUE TITLE
TypeError: Cannot read property 'applySettings' of null

### ISSUE THREAD

**Issue by agudeluca** [Scandit/datacapture-react-native-samples#3]
Guys good morning, Im my company we are trying to implement Scandit
but we got this error 

<img width="573" alt="image" src="https://github.com/Scandit/datacapture-react-native-samples/assets/11505992/2c3e79d9-3fba-457b-9afd-e69bf12f7eda">

are you aware of that? we are running TextCaptureSample project

**Comment by konradgap** [comment]
Hi @agudeluca,

This looks like a null reference issue, which will require some further debugging.

Can you please reach out to us directly and share a few snippets of you code on how you implemented Scandit?

[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by ScanditSupport** [comment]
Hi @agudeluca,

This looks like a null reference issue, which will require some further debugging.

Can you please reach out to us directly and share a few snippets of you code on how you implemented Scandit?

[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
