### ISSUE TITLE
Possible Memory Leak on an older ios device when mounting-unmounting DataCaptureView

### ISSUE THREAD

**Issue by MargusSalk** [Scandit/datacapture-react-native-samples#4]
Hi, we've been trying to upgrade the react-native sdk for a couple of versions now, but keep running into memory issues on one of our test devices - iPhone 6s (ios 15.8.1). Last version we tried was 6.24.0 and we've currently stayed on 6.19.7 which doesn't seem to have those issues.

I verified that this also happens with sample apps. I ran the `BarcodeCaptureViewsSample` app with memory profiler enabled and when toggling between ListPage and FullScreenView the RAM usage increases. I've only profiled it with development builds, but with out production app I was able to crash it when toggling the scanner view repeatedly.

Now with iPhone 11 Pro Max (ios 17.4) the RAM usage was stable when toggling the scanner view.

**Comment by ScanditSupport** [comment]
Hi @MargusSalk,

Thank you for noticing, we are investigating the issue.
In the meantime, as you have already performed some profiling may I ask you to reach out to us directly and share your findings? This way we will be able to to inform you about the progress: https://support.scandit.com/hc/en-us/requests/new  https://support.scandit.com/hc/en-us/requests/new
