### ISSUE TITLE
MatrixScanCount: Uncaptured items

### ISSUE THREAD

**Issue by antonioedinadson** [Scandit/datacapture-react-native-samples#5]
![Imagem do WhatsApp de 2024-06-11 à(s) 13 28 30_719c73f3](https://github.com/Scandit/datacapture-react-native-samples/assets/47501385/65af286a-38b9-446e-916b-dc7def4f69aa)

```
  const barcodeCountListener = {
        didScan: (_: BarcodeCount, session: BarcodeCountSession) => {
            const allRecognizedBarcodes = session.recognizedBarcodes;
        }
   };
```

How can I identify that an item was not captured?

**_Obs: These are in yellow in the image._**

**Comment by ScanditSupport** [comment]
Hi @antonioedinadson,

Generally speaking you cannot get the **value** of an unrecognized barcode, the overlay indicates that another scan is required or the code is unscannable.
However, as I can see - you have already reached out to us via a [support ticket](https://support.scandit.com/hc/en-us/requests/new ), therefore we will continue the conversation there.
