### ISSUE TITLE
Error 1028 - Conflicting Requirements - Expo 52, React Native 76.5

### ISSUE THREAD

**Issue by chathuralakmal** [Scandit/datacapture-react-native-samples#7]
Previously we had following version.
```
 "scandit-react-native-datacapture-barcode": "6.24.1",
  "scandit-react-native-datacapture-core": "6.24.1",
```
But after the new update of Expo and React Native Got 1028 Error. 

```
"scandit-react-native-datacapture-barcode": "7.0.0",
"scandit-react-native-datacapture-core": "7.0.0",
```

I have pretty much same code as this sample without symbologySettings.  
https://github.com/Scandit/datacapture-react-native-samples/blob/master/BarcodeCaptureSimpleSample/app/App.tsx

**Comment by ScanditSupport** [comment]
Hi @chathuralakmal, 

Thank you for reaching out and providing your SDK versions. [Error 1028](https://docs.scandit.com/data-capture-sdk/react-native/core/api/context-status.html#conflicting-requirements) typically occurs when either the same scanning mode is re-attached, or multiple scanning modes are attached to the `DataCaptureContext` at once

If you could please contact Scandit Support using this [request form](https://support.scandit.com/hc/en-us/requests/new), we can assist you further in setting up your project using Expo 52 with React Native 0.76.5 with New Architecture.
